knotdirectory/knotdirectory/knots/urls.py
from django.conf.urls import patterns, url

from .views import KnotListView, KnotDetailView, CreatorListView, CreatorDetailView, CreateKnotView, UpdateKnotView, AutocompleteTagView

urlpatterns = patterns(
    '',
    url(r'^knots/$', KnotListView.as_view(), name="knots.list"),
    url(r'^knots/(?P<tag>.+)/', KnotListView.as_view(), name="knots.list_by_tag"),
    url(r'^knot/(?P<pk>\d+)/', KnotDetailView.as_view(), name="knots.detail"),
    url(r'^creators/', CreatorListView.as_view(), name="creators.list"),
    url(r'^creator/(?P<pk>\d+)/', CreatorDetailView.as_view(), name="creators.detail"),
    url(r'add/', CreateKnotView.as_view(), name='knots.create'),
    url(r'update/(?P<pk>\d+)/', UpdateKnotView.as_view(), name='knots.update'),
    url(r'api/completion/', AutocompleteTagView.as_view(), name='tags.autocomplete'),

)

knotdirectory/knotdirectory/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='index'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt'), name='robots'),
    url(r'', include('social_auth.urls')),

    # Examples:
    # url(r'^$', 'knotdirectory.views.home', name='home'),
    # url(r'^knotdirectory/', include('knotdirectory.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('knotdirectory.knots.urls')),
)

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

knotdirectory/knotdirectory/knots/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib.auth import get_user_model


User = get_user_model()


class Knot(models.Model):
    name = models.CharField(max_length=90, help_text="Commonly accepted name for this tie")
    other_names = models.TextField(help_text="Is this knot known by other names? One name per line, please", blank=True)
    creator_name = models.CharField(max_length=90, help_text="Who should we credit for discovering this tie")
    creator = models.ForeignKey('CreatorProfile', blank=True, null=True, editable=False)
    notes = models.TextField(help_text="Any other information? Markdown text enabled.", blank=True)
    tags = TaggableManager()
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    photo = models.ImageField(upload_to="knotsimages/%Y/%m/", help_text="A photo of the completed tie.")

    def save(self):
        if not self.creator:
            try:
                self.creator = CreatorProfile.objects.get(name=self.creator_name)
            except CreatorProfile.DoesNotExist:
                cp = CreatorProfile()
                cp.name = self.creator_name
                cp.save()
                self.creator = cp
        super(Knot, self).save()

    def get_absolute_url(self):
        return reverse("knots.detail", args=[self.pk, ])

    def __unicode__(self):
        return u'%s' % self.name


class Link(models.Model):
    knot = models.ForeignKey(Knot)
    link = models.URLField(help_text="Link ot the guide")
    name = models.CharField(max_length=90, help_text="A descriptive name for this guide")

    def __unicode__(self):
        return u'Link %s on knot %s' % (self.name, self.knot.name)


class Action(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User)
    when = models.DateTimeField(auto_now=True)
    what = models.TextField()

    def __unicode__(self):
        return u'%s: %s %s %s' % (self.when, self.user, self.what, self.content_object)


class CreatorProfile(models.Model):
    name = models.CharField(max_length=90)
    link_facebook_profile = models.URLField(blank=True)
    link_youtube_channel = models.URLField(blank=True)
    link_website = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    user = models.ForeignKey(User, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse("creators.detail", args=[self.pk, ])

knotdirectory/knotdirectory/knots/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.utils import six

from .models import Knot, Link


def edit_string_for_tags(tags):
    """
    Convert list of Tags into comma-separated list.

    We can't use the one built into django-taggit, because select2 freaks out
    about the space after the comma.
    """
    names = []
    for tag in tags:
        name = tag.name
        if ',' in name or ' ' in name:
            names.append('"%s"' % name)
        else:
            names.append(name)
    return ','.join(sorted(names))


class HiddenTagWidget(forms.HiddenInput):
    """ For use with select2 and ajax tagging """
    def render(self, name, value, attrs=None):
        if value is not None and not isinstance(value, six.string_types):
            value = edit_string_for_tags([o.tag for o in value.select_related("tag")])
        return super(HiddenTagWidget, self).render(name, value, attrs)


class KnotForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(KnotForm, self).__init__(*args, **kwargs)
        print self.fields.keys()
        self.fields['tags'].widget = HiddenTagWidget()

    class Meta:
        model = Knot
        fields = ['name', 'photo', 'other_names', 'creator_name', 'notes', 'tags']


class InlineLinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['name', 'link']

LinkFormset = inlineformset_factory(Knot, Link)

knotdirectory/knotdirectory/knots/views.py
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from taggit.models import Tag
from braces.views import JSONResponseMixin

from models import Knot, CreatorProfile
from .forms import LinkFormset, KnotForm
from .inlineformsetsviews import InlineFormsetsCreateView
from .inlineformsetsviews import InlineFormsetsUpdateView


class KnotListView(ListView):
    model = Knot
    paginate_by = 40

    def get_queryset(self):
        queryset = super(KnotListView, self).get_queryset()
        tag = self.kwargs.get('tag')
        if tag:
            queryset = queryset.filter(tags__name__in=[tag])
        return queryset


class KnotDetailView(DetailView):
    model = Knot


class CreatorListView(ListView):
    model = CreatorProfile
    paginate_by = 10

    def get_queryset(self):
        queryset = super(CreatorListView, self).get_queryset()
        queryset.prefetch_related('knot_set')
        return queryset


class CreatorDetailView(DetailView):
    model = CreatorProfile

    def get_queryset(self):
        queryset = super(CreatorDetailView, self).get_queryset()
        queryset.prefetch_related('knot_set')
        return queryset


class CreateKnotView(InlineFormsetsCreateView):
    model = Knot
    form = KnotForm
    formsets = [LinkFormset, ]

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CreateKnotView, self).dispatch(*args, **kwargs)


class UpdateKnotView(InlineFormsetsUpdateView):
    model = Knot
    form_class = KnotForm
    formsets = [LinkFormset, ]

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UpdateKnotView, self).dispatch(*args, **kwargs)


class AutocompleteTagView(JSONResponseMixin, View):
    def get(self, request, *args, **kwargs):
        q = self.request.GET.get('q', '')
        tags = Tag.objects.filter(name__istartswith=q)
        context = map(lambda x: {'id': x.name, 'text': x.name}, tags)
        return self.render_json_response(context)

knotdirectory/knotdirectory/knots/templates/knots/creatorprofile_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block page_title %} {{ object.name}} {% endblock %}
{% block content %}
<div class="row">
    <div class="span5">{{ object.bio }}</div>
    <div class="span5">
        <ul>
            {% if object.email %}<li><a href="mailto:{{ object.email }}"><i class="icon-envelope-alt"></i> email {{ object.name }}</a></li>{% endif %}
            {% if object.link_facebook %}<li><a href="{{ object.link_facebook }}"><i class="icon-facebook"></i> {{ object.name }} on facebook</a></li>{% endif%}
            {% if object.link_youtube_channel %}<li><a href="{{ object.link_youtube_channel }}"><i class="icon-youtube"></i> {{ object.name }} on youtube</a></li>{% endif %}
                {% if object.link_internet %}<li><a href="{{ object.link_internet }}"><i class="icon-globe"></i> {{ object.name }} on the internet</a></li>{% endif %}
        </ul>
    </div>
</div>
<div class="row">
    <div class="span10">
        <ul class="thumbnails">
            {% for knot in object.knot_set.all %}
            <li class="span2">
            <div class="thumbnail">
                <a href="{{ knot.get_absolute_url }}">
                    <img src="{% thumbnail knot.photo "202x202" %}">
                    <h4>{{ knot.name }}</h4>
                </a>
            </div>
        </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

knotdirectory/knotdirectory/knots/templates/knots/creatorprofile_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block page_title %}Creators{% endblock %}
{% block content %}
{% for creator in object_list %}
<div class="row">
    <div class="span10">
        <h3><a href="{{ creator.get_absolute_url }}">{{ creator.name}}</a></h3>
        <ul class="thumbnails">
            {% for knot in creator.knot_set.all|slice:":4" %}
            <li class="span2">
            <div class="thumbnail">
                <a href="{{ knot.get_absolute_url }}">
                    <img src="{% thumbnail knot.photo "202x202" %}">
                    <h4>{{ knot.name }}</h4>
                </a>
            </div>
        </div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endfor %}
{% endblock content %}

knotdirectory/knotdirectory/knots/templates/knots/knot_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load linktags %}
{% block page_title %}{{ object.name }}
<span="pull-right"><a href="{% url "knots.update" object.pk %}" class="btn-small btn"><i class="icon-pencil"></i> Update</a></span>
{% endblock %}
{% block content %}
<div class="row">
    <div class="span9 well">
        <div class="row">
    <div class="span5">
        <div class="fb-like" data-href="{{request.build_absolute_uri}}" data-width="150" data-layout="button_count" data-show-faces="true" data-send="true"></div>
        <h3 class="muted">By {{ object.creator }}</h3>
        {% if object.other_names %}
        <h4>Also known as...</h4>
        <p> {{ object.other_names|linebreaksbr}}</p>
        {% endif %}
        {% if object.notes %}
        <h4>Notes</h4>
        <p>{{ object.notes }}</p>
        {% endif %}
        {% if object.tags.all %}
        <h4>Tags</h4>
        {% for tag in object.tags.all %}<a href="{% url 'knots.list_by_tag' tag.slug %}">{{tag.name}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
        {% endif %}
    </div>
    <div class="span4"><a href="{{object.photo.url}}"><img src="{% thumbnail object.photo "300x300" %}"></a></div>
</div>
</div>
        <h3>Guides</h3>
        <ul>
            {% for link in object.link_set.all %}
            <li>{% format_link link %}</li>
            {% endfor %}
        </ul>
</div>
{% endblock content %}

knotdirectory/knotdirectory/knots/templates/knots/knot_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block page_title %}{% if object %}{{ object.name }}{% else %}Add New Knot{% endif %}{% endblock %}

{% block content %}
<form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{% include '_form.html' with form=form request=request only %}
<input type="hidden" id="id_tags_auto">
{% for formset in formsets %}
{{ formset.non_form_errors.as_ul }}
<table class="table table-striped table-bordered table-hover">
    {% for formset_form in formset.forms %}
    {% if forloop.first %}
    <thead>
        <tr>
            {% for field in formset_form.visible_fields %}
            <th>{{ field.label|capfirst }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% endif %}
    <tr class="form-horizontal {% cycle row1,row2 %}">
        {% for field in formset_form.visible_fields %}
        <td>
            {# include hidden fields #}
            {% if forloop.first %}
            {% for hidden in formset_form.hidden_fields %}
            {{ hidden}}
            {% endfor %}
            {% endif %}
            {{ field.errors.as_ul}}
            {{ field }}
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{{ formset.management_form}}
{% endfor %}
<button type="submit">Save</button>
</form>
{% endblock %}
{% block extra_js %}
<script src="{% static 'js/select2.min.js' %}"></script>
<script type="text/javascript">
console.log("This piece of javascript exists!");
$(function() {
    console.log("document ready!");
    $("#id_tags").select2({
        width: '220px',
        //tags: {{ tags|safe }},
        //tokenSeparators: [",", " "],
        placeholder: "Please tag at least the project type (Eg bracelet)",
        tokenSeparators: [',', ' '],
        multiple: true,
        createSearchChoice: function (term, data) {
            if ($(data).filter(function () {
                return this.text.localeCompare(term) === 0;
            }).length === 0) {
                return {
                    id: term,
                    text: term
                };
            }
        },
        initSelection : function (element, callback) {
            var data = [];
            $(element.val().split(",")).each(function () {
                data.push({id: this, text: this});
            });
            callback(data);
        },
        ajax: {
            url: '{% url 'tags.autocomplete' %}',
            dataType: "json",
            data: function(term, page) {
                return {
                    q: term
                };
            },
            results: function(data, page) {
                console.log(data)
                return {
                    results: data
                };
            }
        }
    });
});
</script>
{% endblock extra_js %}

knotdirectory/knotdirectory/knots/templates/knots/knot_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block page_title %}Browse Knots...{% endblock %}

{% block content %}

{% if object_list %}
    <ul class="thumbnails">
    {% for knot in object_list %}
    <li class="span3">
    <div class="thumbnail">
        <a href="{{ knot.get_absolute_url }}">
            <img src="{% thumbnail knot.photo "252x252" %}">
            <h4>{{ knot.name }}</h4>
        </a>
    </div>
    </li>

    {% endfor %}

    {% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
    {% endif %}
{% else %}
    <p>Sorry, there aren't any knots here.</p>
{% endif %}

{% endblock content %}

knotdirectory/templates/_form.html
{% for field in form %}
<div class="control-group{% if field.errors %} error{% endif %}">
    <label class="control-label">{{ field.label }}{% if field.field.required %} *{% endif %}</label>
    <div class="controls">{{ field }}
        <span class="help-inline">
            {% if field.errors %}{% for error in field.errors %}<p class="">{{ error }}</p>{% endfor %}{% endif %}
            {% if field.help_text %}<p><small>{{ field.help_text }}</small></p>{% endif %}
        </span>
    </div>
</div>
{% endfor %}
<div class="control-group">
    <em>Fields marked with * are required</em>
</div>

knotdirectory/templates/about.html
{% extends 'base.html' %}

{% block page_title %}About Knotcrafters.com{% endblock %}
{% block content %}
<p>Knotcrafters.com is a site dedicated to making it easy for new and old
craftspeople alike to find guides to tying all the wonderful and wacky ties
our fantastic community has created. This site is community driven, which
means we need you to help out! If you'd like to help, the website is open
source, so you can help out with the code by submitting a pull request to
our <a href="#">git repo</a>, or you can help <a href="#">submit new ties</a>.

<p>Knotcrafters.com is build and maintained by Justin Steward. The knots and
ties documented on this site were created by various members of our community.
We do our best to make sure the right people get attributed for each tie on
our site, but if we got it wrong, please <a href="/contact/">contact us</a>.</p>
{% endblock content %}

knotdirectory/templates/base.html
{% load staticfiles %}
{% load navtags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Knotcrafters{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" href="{% static 'ico/touch-icon-ipad.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'ico/apple-touch-icon-72-precomposed.png' %}" type="image/png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'ico/apple-touch-icon-114-precomposed.png' %}" type="image/png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'ico/apple-touch-icon-144-precomposed.png' %}" type="image/png">
    <link rel="icon" href="{% static 'ico/favicon.png' %}" type="image/png"> 

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/select2.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to project.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=158263727702947";
          fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Knotcrafters.com</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li class="{% navactive request 'index' %}"><a href="/">Home</a></li>
                <li class="{% navactive request 'knots.list knots.detail knots.list_by_tag' %}"><a href="/knots/">Knots</a></li>
              <li class="{% navactive request 'about' %}"><a href="/about">About</a></li>
              <li class="{% navactive request 'contact' %}"><a href="/contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
                <li>{% if request.user.is_authenticated %}<p class="navbar-text">Welcome, {{ request.user.first_name }}</p>{% else %}<a href="/login/facebook/?next={{request.path}}">Log in with Facebook</a>{% endif %}</li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="offset1 span11"><h1>{% block page_title %}Welcome to Knotcrafters{% endblock page_title %}</h1></div>
        <div class="row">
            <div class="span2">
                <div class="well well-small">
                    <ul class="nav nav-list">
                        <li class="nav-header">Browse...</li>
                        <li><a href="{% url "knots.list" %}">Everything</a></li>
                        <li><a href="{% url "knots.list_by_tag" "bracelet" %}">Bracelets</a></li>
                        <li><a href="{% url "knots.list_by_tag" "keychain" %}">Keychains</a></li>
                        <li><a href="{% url "knots.list_by_tag" "lanyard" %}">Lanyards</a></li>
                        <li><a href="#">By Creator</a></li>
                        <li class="nav-header">Help out...</li>
                        <li><a href="{% url "knots.create" %}">Add a Tie</a></li>
                    </ul>
                </div>
            </div>
            <div class="span10">


                {% block content %}
                <p>Knotcrafters.com is a website put together by the community for the
                community. Here you can find a searchable index of tutorials for knots
                and ties discovered, invented, or otherwise found by the paracord
                community.</p>
                <p>We are a very new site, so if you want to help out, please 
                <a href="/about">do so!</a></p>
                {% endblock content %}
            </div>
        </div>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>

    {% block extra_js %}{% endblock extra_js %}
  </body>
</html>

knotdirectory/templates/contact.html
{% extends 'base.html' %}
{% block page_title %}Contact us{% endblock %}
{% block content %}
<p>Knotcrafters is a community site. Quesitons are best directed to the following Facebook groups:
<ul>
    <li><a href="https://www.facebook.com/groups/131626637036149/">Knot Just Paracord</a></li>
    <li><a href="https://www.facebook.com/groups/123589031181901/">Krafters Kingdom</a></li>
    <li><a href="https://www.facebook.com/groups/194548893899579/">Parachute Cord Crafters</a></li>
</ul>
</p>
<p>If you want to get in touch with the developer, you can reach me by emailing <a href="mailto:justin@justinsteward.com">justin@justinsteward.com</a> or finding me on <a href="http://www.facebook.com/althalus87">facebook</a>.</p>
{% endblock content %}